In [2]:
%load_ext autoreload
%autoreload 2

In [16]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings("ignore")

# 13.1.0 Foundations for efficiencies

## 13.1.2 Pop quiz: what is efficient

In the context of this course, what is meant by efficient Python code?

R:/ Code that executes quickly for the task at hand, minimizes the memory footprint and follows Python's coding style principles. Writing efficient Python code minimizes runtime and memory usage while also following the idioms in the Zen of Python.

## 13.1.3 A taste of things to come

In [5]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1

In [7]:
# Print the list created using the Non-Pythonic approach
i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [8]:
# Print the list created by looping over the contents of names
better_list = []
for name in names:
    if len(name) >= 6:
        better_list.append(name)
print(better_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [9]:
# Print the list created by using list comprehension
best_list = [name for name in names if len(name) >= 6]
print(best_list)

['Kramer', 'Elaine', 'George', 'Newman']


## 13.1.4 Zen of Python

What is the 7th idiom of the Zen of Python?

R:/ Readability counts. Python has a design philosophy that emphasizes readability. Throughout the course, you'll see that writing efficient Python code goes hand in hand with writing code that is easy to understand. Faster code is good, but faster & readable code is best!

## 13.1.6 Built-in practice: range()

In [10]:
# Create a range object that goes from 0 to 5
nums = range(6)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 11 by unpacking a range object
nums_list2 = [*range(1,12,2)]
print(nums_list2)

<class 'range'>
[0, 1, 2, 3, 4, 5]
[1, 3, 5, 7, 9, 11]


## 13.1.7 Built-in practice: enumerate()

In [11]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

indexed_names = []
for i in range(len(names)):
    index_name = (i, names[i])
    indexed_names.append(index_name)

[(0,'Jerry'),(1,'Kramer'),(2,'Elaine'),(3,'George'),(4,'Newman')]

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]

In [12]:
# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, 1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


## 13.1.8 Built-in practice: map()

In [13]:
names_uppercase = []

for name in names:
  names_uppercase.append(name.upper())

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']

In [14]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*names_map]

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


## 13.1.9 Practice with NumPy arrays

In [17]:
nums = np.array([[ 1,  2,  3,  4,  5],
                 [ 6,  7,  8,  9, 10]])

In [18]:
# Print second row of nums
print(nums[1,:])

# Print all elements of nums that are greater than six
print(nums[nums > 6])

# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

# Replace the third column of nums
nums[:, 2] = nums[:, 2] + 1
print(nums)

[ 6  7  8  9 10]
[ 7  8  9 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


Question?

When compared to a list object, what are two advantages of using a numpy array?

R./ A numpy array contains homogeneous data dtypes (which reduces memory consumption) and provides the ability to apply operations on all elements through broadcasting. You're slicing numpy arrays like a pro and learning how to take advantage of NumPy's broadcasting concept. Using numpy arrays allows you to take advantage of an array's memory efficient nature and easily perform mathematical operations on your data.

## 13.1.10 Bringing it all together: Festivus!

In [54]:
def welcome_guest(guest_arrivals):
    return f'Welcome to Festivus {guest_arrivals[0]} You\'re {guest_arrivals[1]} min late'

In [19]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

print(arrival_times)

[10, 20, 30, 40, 50]


In [20]:
# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

print(new_times)

[ 7 17 27 37 47]


In [55]:
# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

print(guest_arrivals)

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


In [56]:
# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)

guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')

Welcome to Festivus Jerry You're 7 min late
Welcome to Festivus Kramer You're 17 min late
Welcome to Festivus Elaine You're 27 min late
Welcome to Festivus George You're 37 min late
Welcome to Festivus Newman You're 47 min late


In [6]:
print('Ok_')

Ok_
